name: Docker testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      UID: 0

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: 'recursive'

      - name: Environment info
        run: |
          docker-compose --version

      - name: Build base image, start containers, and wait for services
        run: |
          docker-compose up --build -d
          # Hang tight until MySQL appears to be working
          docker-compose exec -T web urlwait mysql://root:kuma@mysql:3306/developer_mozilla_org 30

      - name: Compile locales
        run: docker-compose exec -T web make localecompile

      - name: DB migrations
        run: |
          docker-compose exec -T web ./manage.py migrate
          # Essentially compares **/models.py with **/migrations/*.py and
          # makes sure the developer didn't forget to create a new migration.
          docker-compose exec -T web ./manage.py makemigrations --check --dry-run

      - name: Run Python tests
        run: |
          # TODO: Run the `make coveragetest` only if it's a pull request.
          # We might be able to use something
          # like `if [ ${{ github.head_ref}} eq 'master']` but not sure.
          # Slower...
          docker-compose exec -T web make coveragetest
          # Faster...
          #docker-compose exec -T web make test

      - name: Submit code coverage
        run: |
          bash <(curl -s --retry 3 --retry-connrefused https://codecov.io/bash)

      - name: Run localerefresh
        run: |
          set -e
          docker-compose run testing make localeextract
          docker-compose run testing make localetest
          docker-compose run testing make localecompile

          cd locale
          export GIT_PAGER=cat
          git diff -G "^msgid " templates/LC_MESSAGES
